name: yag_model

channels:
  - conda-forge

dependencies:
  - python=3.11

  # build tools
  - cmake
  - ninja
  - compilers
  - pkg-config
  - scikit-build-core

  # python
  - numpy
  - scipy
  - matplotlib
  - ipykernel
  - pip
  - optuna
  - optuna-dashboard

  # c++ libs
  - pybind11
  - xtensor
  - xtensor-python
  - xtl
  - libopenblas
  - blas-devel

  # testing
  - catch2